### ISSUE TITLE
Downloading from YouTube fails with The operation couldn’t be completed. (domain error 0.)

### ISSUE THREAD

**Issue by crazyguyonabike** [youstanzr/YouTag#74]
Starting the required downloads for song
2020-07-30 08:52:04.233058-0700 YouTag[29737:2491621] [ProcessSuspension] 0x10aee1f20 - ProcessAssertion::processAssertionWasInvalidated()
Downloaded successfully to /var/mobile/Containers/Data/Application/F71219F3-7C6E-40A3-8F20-CE87B717028E/Documents/yt_88sARuFu-tcCIHDCDECBGJFB.jpg
Downloaded successfully to /var/mobile/Containers/Data/Application/F71219F3-7C6E-40A3-8F20-CE87B717028E/Documents/yt_88sARuFu-tcCIHDCDECBGJFB.mp4
Extracting audio from video
**The operation couldn’t be completed. (domain error 0.)**
Removed file: /var/mobile/Containers/Data/Application/F71219F3-7C6E-40A3-8F20-CE87B717028E/Documents/yt_88sARuFu-tcCIHDCDECBGJFB.mp4
2020-07-30 08:52:29.674086-0700 YouTag[29737:2491621] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2020-07-30 08:52:29.682110-0700 YouTag[29737:2491621] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service

**Comment by youstanzr** [comment]
Is this issue with all download or this single song only? Can you regenerate it?

**Comment by cristea2017** [comment]
just update this pod to the last version : 
[https://github.com/0xced/XCDYouTubeKit](url)

**Comment by cristea2017** [comment]
> Starting the required downloads for song
> 2020-07-30 08:52:04.233058-0700 YouTag[29737:2491621] [ProcessSuspension] 0x10aee1f20 - ProcessAssertion::processAssertionWasInvalidated()
> Downloaded successfully to /var/mobile/Containers/Data/Application/F71219F3-7C6E-40A3-8F20-CE87B717028E/Documents/yt_88sARuFu-tcCIHDCDECBGJFB.jpg
> Downloaded successfully to /var/mobile/Containers/Data/Application/F71219F3-7C6E-40A3-8F20-CE87B717028E/Documents/yt_88sARuFu-tcCIHDCDECBGJFB.mp4
> Extracting audio from video
> **The operation couldn’t be completed. (domain error 0.)**
> Removed file: /var/mobile/Containers/Data/Application/F71219F3-7C6E-40A3-8F20-CE87B717028E/Documents/yt_88sARuFu-tcCIHDCDECBGJFB.mp4
> 2020-07-30 08:52:29.674086-0700 YouTag[29737:2491621] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
> 2020-07-30 08:52:29.682110-0700 YouTag[29737:2491621] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service

show some code !!!

**Comment by youstanzr** [comment]
@cristea2017 The app already has the code to download and convert to audio so there is nothing you have to add

**Comment by cristea2017** [comment]
> @cristea2017 The app already has the code to download and convert to audio so there is nothing you have to add

ok but issue is 

> Downloading from YouTube fails with ...

So download process have some errors , my example works 100%

**Comment by youstanzr** [comment]
@cristea2017 Have you tested the app and faced the same issue? cause I am using the app on multiple devices and none is facing any issues

**Comment by youstanzr** [comment]
Issue is closed due to no reply from the issue submitter
