### ISSUE TITLE
"Video Unavailable" error when downloading

### ISSUE THREAD

**Issue by Chitpixel** [youstanzr/YouTag#78]
When I tried downloading any video from YouTube, I got a popup saying "Video Unavailable." Upon further digging, it seems like [XCDYouTubeKit](https://github.com/0xced/XCDYouTubeKit/releases/tag/2.15.2) received an update to resolve this. I fixed it by updating all Swift dependencies by File -> Swift Packages -> Update to Latest Package Versions. Is this something a Pull Request should be submitted for?

**Comment by youstanzr** [comment]
Yes you can pull request for updating dependencies but you have to update the version and build as well when you do so. I will be doing the changes now and pull it to master. Thanks for letting me know, feel free to look up the issues and contribute as you like 👍
